services:
  acquire:
    container_name: backend-acquire
    build:
      context: ./acquire
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_DB=0
    volumes:
      - /var/log/acquire:/app/game_logs
    networks:
      - global-network
    restart: always

  splendor:
    container_name: backend-splendor
    build:
      context: ./splendor
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_DB=1
    volumes:
      - /var/log/splendor:/app/game_logs
    networks:
      - global-network
    restart: always

networks:
  global-network:
    external: true
