version: "3.8"
services:
  go-game:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
    restart: always

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always