package const_data

import (
	"go-game/entities"
)

var SplendorCards = map[int][]entities.NormalCard{
	1: {
		{ID: 0, Level: 1, Bonus: "Black", Points: 0, Cost: map[string]int{"Blue": 1, "Green": 1, "Red": 1, "White": 1}, State: entities.CardStateHidden},
		{ID: 1, Level: 1, Bonus: "Black", Points: 0, Cost: map[string]int{"Blue": 2, "Green": 1, "Red": 1, "White": 1}, State: entities.CardStateHidden},
		{ID: 2, Level: 1, Bonus: "Black", Points: 0, Cost: map[string]int{"Blue": 2, "Red": 1, "White": 2}, State: entities.CardStateHidden},
		{ID: 3, Level: 1, Bonus: "Black", Points: 0, Cost: map[string]int{"Black": 1, "Green": 1, "Red": 3}, State: entities.CardStateHidden},
		{ID: 4, Level: 1, Bonus: "Black", Points: 0, Cost: map[string]int{"Green": 2, "Red": 1}, State: entities.CardStateHidden},
		{ID: 5, Level: 1, Bonus: "Black", Points: 0, Cost: map[string]int{"Green": 2, "White": 2}, State: entities.CardStateHidden},
		{ID: 6, Level: 1, Bonus: "Black", Points: 0, Cost: map[string]int{"Green": 3}, State: entities.CardStateHidden},
		{ID: 7, Level: 1, Bonus: "Black", Points: 1, Cost: map[string]int{"Blue": 4}, State: entities.CardStateHidden},
		{ID: 8, Level: 1, Bonus: "Blue", Points: 0, Cost: map[string]int{"Black": 1, "Green": 1, "Red": 1, "White": 1}, State: entities.CardStateHidden},
		{ID: 9, Level: 1, Bonus: "Blue", Points: 0, Cost: map[string]int{"Black": 1, "Green": 1, "Red": 2, "White": 1}, State: entities.CardStateHidden},
		{ID: 10, Level: 1, Bonus: "Blue", Points: 0, Cost: map[string]int{"Green": 2, "Red": 2, "White": 1}, State: entities.CardStateHidden},
		{ID: 11, Level: 1, Bonus: "Blue", Points: 0, Cost: map[string]int{"Blue": 1, "Green": 3, "Red": 1}, State: entities.CardStateHidden},
		{ID: 12, Level: 1, Bonus: "Blue", Points: 0, Cost: map[string]int{"Black": 2, "White": 1}, State: entities.CardStateHidden},
		{ID: 13, Level: 1, Bonus: "极", Points: 0, Cost: map[string]int{"Black": 2, "Green": 2}, State: entities.CardStateHidden},
		{ID: 14, Level: 1, Bonus: "Blue", Points: 0, Cost: map[string]int{"Black": 3}, State: entities.CardStateHidden},
		{ID: 15, Level: 1, Bonus: "Blue", Points: 1, Cost: map[string]int{"Red": 4}, State: entities.CardStateHidden},
		{ID: 16, Level: 1, Bonus: "White", Points: 0, Cost: map[string]int{"Black": 1, "Blue": 1, "Green": 1, "Red": 1}, State: entities.CardStateHidden},
		{ID: 17, Level: 1, Bonus: "White", Points: 0, Cost: map[string]int{"Black": 1, "Blue": 1, "Green": 2, "Red": 1}, State: entities.CardStateHidden},
		{ID: 18, Level: 1, Bonus: "White", Points: 0, Cost: map[string]int{"Black": 1, "Blue": 2, "Green": 2}, State: entities.CardStateHidden},
		{ID: 19, Level: 1, Bonus: "White", Points: 0, Cost: map[string]int{"Black": 1, "White": 3}, State: entities.CardStateHidden},
		{ID: 20, Level: 1, Bonus: "White", Points: 0, Cost: map[string]int{"Black": 1, "Red": 2}, State: entities.CardStateHidden},
		{ID: 21, Level: 1, Bonus: "White", Points: 0, Cost: map[string]int{"Black": 2, "Blue": 2}, State: entities.CardStateHidden},
		{ID: 22, Level: 1, Bonus: "White", Points: 0, Cost: map[string]int{"Blue": 3}, State: entities.CardStateHidden},
		{ID: 23, Level: 1, Bonus: "White", Points: 1, Cost: map[string]int{"Green": 4}, State: entities.CardStateHidden},
		{ID: 24, Level: 1, Bonus: "Green", Points: 0, Cost: map[string]int{"Black": 1, "Blue": 1, "Red": 1, "White": 1}, State: entities.CardStateHidden},
		{ID: 25, Level: 1, Bonus: "Green", Points: 0, Cost: map[string]int{"Black": 2, "Blue": 1, "Red": 1, "White": 1}, State: entities.CardStateHidden},
		{ID: 26, Level: 1, Bonus: "Green", Points: 0, Cost: map[string]int{"Black": 2, "Blue": 1, "Red": 2}, State: entities.CardStateHidden},
		{ID: 27, Level: 1, Bonus: "Green", Points: 0, Cost: map[string]int{"Blue": 3, "Green": 1, "White": 1}, State: entities.CardStateHidden},
		{ID: 28, Level: 1, Bonus: "Green", Points: 0, Cost: map[string]int{"Blue": 1, "White": 2}, State: entities.CardStateHidden},
		{ID: 29, Level: 1, Bonus: "Green", Points: 0, Cost: map[string]int{"Blue": 2, "Red": 2}, State: entities.CardStateHidden},
		{ID: 30, Level: 1, Bonus: "Green", Points: 0, Cost: map[string]int{"Red": 3}, State: entities.CardStateHidden},
		{ID: 31, Level: 1, Bonus: "Green", Points: 1, Cost: map[string]int{"Black": 4}, State: entities.CardStateHidden},
		{ID: 32, Level: 1, Bonus: "Red", Points: 0, Cost: map[string]int{"Black": 1, "Blue": 1, "Green": 1, "White": 1}, State: entities.CardStateHidden},
		{ID: 33, Level: 1, Bonus: "Red", Points: 0, Cost: map[string]int{"Black": 1, "Blue": 1, "Green": 1, "White": 2}, State: entities.CardStateHidden},
		{ID: 34, Level: 1, Bonus: "Red", Points: 0, Cost: map[string]int{"Black": 2, "Green": 1, "White": 2}, State: entities.CardStateHidden},
		{ID: 35, Level: 1, Bonus: "Red", Points: 0, Cost: map[string]int{"Black": 3, "Red": 1, "White": 1}, State: entities.CardStateHidden},
		{ID: 36, Level: 1, Bonus: "Red", Points: 0, Cost: map[string]int{"Blue": 2, "Green": 1}, State: entities.CardStateHidden},
		{ID: 37, Level: 1, Bonus: "Red", Points: 0, Cost: map[string]int{"White": 2, "Red": 2}, State: entities.CardStateHidden},
		{ID: 38, Level: 1, Bonus: "Red", Points: 0, Cost: map[string]int{"White": 3}, State: entities.CardStateHidden},
		{ID: 39, Level: 1, Bonus: "Red", Points: 1, Cost: map[string]int{"White": 4}, State: entities.CardStateHidden},
	},

	2: {
		{ID: 40, Level: 2, Bonus: "Black", Points: 1, Cost: map[string]int{"Blue": 2, "Green": 2, "White": 3}, State: entities.CardStateHidden},
		{ID: 41, Level: 2, Bonus: "Black", Points: 1, Cost: map[string]int{"Black": 2, "Green": 3, "White": 3}, State: entities.CardStateHidden},
		{ID: 42, Level: 2, Bonus: "Black", Points: 2, Cost: map[string]int{"Blue": 1, "Green": 4, "Red": 2}, State: entities.CardStateHidden},
		{ID: 43, Level: 2, Bonus: "Black", Points: 2, Cost: map[string]int{"Green": 5, "Red": 3}, State: entities.CardStateHidden},
		{ID: 44, Level: 2, Bonus: "Black", Points: 2, Cost: map[string]int{"White": 5}, State: entities.CardStateHidden},
		{ID: 45, Level: 2, Bonus: "Black", Points: 3, Cost: map[string]int{"Black": 6}, State: entities.CardStateHidden},
		{ID: 46, Level: 2, Bonus: "Blue", Points: 1, Cost: map[string]int{"Blue": 2, "Green": 2, "Red": 3}, State: entities.CardStateHidden},
		{ID: 47, Level: 2, Bonus: "Blue", Points: 1, Cost: map[string]int{"Black": 3, "Blue": 2, "Green": 3}, State: entities.CardStateHidden},
		{ID: 48, Level: 2, Bonus: "Blue", Points: 2, Cost: map[string]int{"Blue": 3, "White": 5}, State: entities.CardStateHidden},
		{ID: 49, Level: 2, Bonus: "Blue", Points: 2, Cost: map[string]int{"Black": 4, "Red": 1, "White": 2}, State: entities.CardStateHidden},
		{ID: 50, Level: 2, Bonus: "Blue", Points: 2, Cost: map[string]int{"Blue": 5}, State: entities.CardStateHidden},
		{ID: 51, Level: 2, Bonus: "Blue", Points: 3, Cost: map[string]int{"Blue": 6}, State: entities.CardStateHidden},
		{ID: 52, Level: 2, Bonus: "White", Points: 1, Cost: map[string]int{"Black": 2, "Green": 3, "Red": 2}, State: entities.CardStateHidden},
		{ID: 53, Level: 2, Bonus: "White", Points: 1, Cost: map[string]int{"Blue": 3, "Red": 3, "White": 2}, State: entities.CardStateHidden},
		{ID: 54, Level: 2, Bonus: "White", Points: 2, Cost: map[string]int{"Black": 2, "Green": 1, "Red": 4}, State: entities.CardStateHidden},
		{ID: 55, Level: 2, Bonus: "White", Points: 2, Cost: map[string]int{"Black": 3, "Red": 5}, State: entities.CardStateHidden},
		{ID: 56, Level: 2, Bonus: "White", Points: 2, Cost: map[string]int{"Red": 5}, State: entities.CardStateHidden},
		{ID: 57, Level: 2, Bonus: "White", Points: 3, Cost: map[string]int{"White": 6}, State: entities.CardStateHidden},
		{ID: 58, Level: 2, Bonus: "Green", Points: 1, Cost: map[string]int{"Green": 2, "Red": 3, "White": 3}, State: entities.CardStateHidden},
		{ID: 59, Level: 2, Bonus: "Green", Points: 1, Cost: map[string]int{"Black": 2, "Blue": 3, "White": 2}, State: entities.CardStateHidden},
		{ID: 60, Level: 2, Bonus: "Green", Points: 2, Cost: map[string]int{"Black": 1, "Blue": 2, "White": 4}, State: entities.CardStateHidden},
		{ID: 61, Level: 2, Bonus: "Green", Points: 2, Cost: map[string]int{"Blue": 5, "Green": 3}, State: entities.CardStateHidden},
		{ID: 62, Level: 2, Bonus: "Green", Points: 2, Cost: map[string]int{"Green": 5}, State: entities.CardStateHidden},
		{ID: 63, Level: 2, Bonus: "Green", Points: 3, Cost: map[string]int{"Green": 6}, State: entities.CardStateHidden},
		{ID: 64, Level: 2, Bonus: "Red", Points: 1, Cost: map[string]int{"Black": 3, "Red": 2, "White": 2}, State: entities.CardStateHidden},
		{ID: 65, Level: 2, Bonus: "Red", Points: 1, Cost: map[string]int{"Black": 3, "Blue": 3, "Red": 2}, State: entities.CardStateHidden},
		{ID: 66, Level: 2, Bonus: "Red", Points: 2, Cost: map[string]int{"Blue": 4, "Green": 2, "White": 1}, State: entities.CardStateHidden},
		{ID: 67, Level: 2, Bonus: "Red", Points: 2, Cost: map[string]int{"Black": 5, "White": 3}, State: entities.CardStateHidden},
		{ID: 68, Level: 2, Bonus: "Red", Points: 2, Cost: map[string]int{"Black": 5}, State: entities.CardStateHidden},
		{ID: 69, Level: 2, Bonus: "Red", Points: 3, Cost: map[string]int{"Red": 6}, State: entities.CardStateHidden},
	},

	3: {
		{ID: 70, Level: 3, Bonus: "Black", Points: 3, Cost: map[string]int{"Blue": 3, "Green": 5, "Red": 3, "White": 3}, State: entities.CardStateHidden},
		{ID: 71, Level: 3, Bonus: "Black", Points: 4, Cost: map[string]int{"Red": 7}, State: entities.CardStateHidden},
		{ID: 72, Level: 3, Bonus: "Black", Points: 4, Cost: map[string]int{"Black": 3, "Green": 3, "极": 6}, State: entities.CardStateHidden},
		{ID: 73, Level: 3, Bonus: "Black", Points: 5, Cost: map[string]int{"Black": 3, "Red": 7}, State: entities.CardStateHidden},
		{ID: 74, Level: 3, Bonus: "Blue", Points: 3, Cost: map[string]int{"Black": 5, "Green": 3, "Red": 3, "White": 3}, State: entities.CardStateHidden},
		{ID: 75, Level: 3, Bonus: "Blue", Points: 4, Cost: map[string]int{"White": 7}, State: entities.CardStateHidden},
		{ID: 76, Level: 3, Bonus: "Blue", Points: 4, Cost: map[string]int{"Black": 3, "Blue": 3, "White": 6}, State: entities.CardStateHidden},
		{ID: 77, Level: 3, Bonus: "Blue", Points: 5, Cost: map[string]int{"Blue": 3, "White": 7}, State: entities.CardStateHidden},
		{ID: 78, Level: 3, Bonus: "White", Points: 3, Cost: map[string]int{"Black": 3, "Blue": 3, "Green": 3, "Red": 5}, State: entities.CardStateHidden},
		{ID: 79, Level: 3, Bonus: "White", Points: 4, Cost: map[string]int{"Black": 7}, State: entities.CardStateHidden},
		{ID: 80, Level: 3, Bonus: "White", Points: 4, Cost: map[string]int{"Black": 6, "Red": 3, "White": 3}, State: entities.CardStateHidden},
		{ID: 81, Level: 3, Bonus: "White", Points: 5, Cost: map[string]int{"Black": 7, "White": 3}, State: entities.CardStateHidden},
		{ID: 82, Level: 3, Bonus: "Green", Points: 3, Cost: map[string]int{"Black": 3, "Blue": 3, "Red": 3, "White": 5}, State: entities.CardStateHidden},
		{ID: 83, Level: 3, Bonus: "Green", Points: 4, Cost: map[string]int{"Blue": 7}, State: entities.CardStateHidden},
		{ID: 84, Level: 3, Bonus: "Green", Points: 4, Cost: map[string]int{"Blue": 6, "Green": 3, "White": 3}, State: entities.CardStateHidden},
		{ID: 85, Level: 3, Bonus: "Green", Points: 5, Cost: map[string]int{"Blue": 7, "Green": 3}, State: entities.CardStateHidden},
		{ID: 86, Level: 3, Bonus: "Red", Points: 3, Cost: map[string]int{"Black": 3, "Blue": 5, "Green": 3, "White": 3}, State: entities.CardStateHidden},
		{ID: 87, Level: 3, Bonus: "Red", Points: 4, Cost: map[string]int{"Green": 7}, State: entities.CardStateHidden},
		{ID: 88, Level: 3, Bonus: "Red", Points: 4, Cost: map[string]int{"Blue": 3, "Green": 6, "Red": 3}, State: entities.CardStateHidden},
		{ID: 89, Level: 3, Bonus: "Red", Points: 5, Cost: map[string]int{"Green": 7, "Red": 3}, State: entities.CardStateHidden},
	},
}

var NobleTilesList = []entities.NobleCard{
	// Pairwise 4+4
	{ID: "N1", Cost: map[string]int{"Red": 4, "Green": 4}, Points: 3, State: entities.CardStateHidden},
	{ID: "N2", Cost: map[string]int{"Green": 4, "White": 4}, Points: 3, State: entities.CardStateHidden},
	{ID: "N3", Cost: map[string]int{"White": 4, "Blue": 4}, Points: 3, State: entities.CardStateHidden},
	{ID: "N4", Cost: map[string]int{"Blue": 4, "Black": 4}, Points: 3, State: entities.CardStateHidden},
	{ID: "N5", Cost: map[string]int{"Black": 4, "Red": 4}, Points: 3, State: entities.CardStateHidden},

	// Triple-sequence 3+3+3
	{ID: "N6", Cost: map[string]int{"Red": 3, "Green": 3, "White": 3}, Points: 3, State: entities.CardStateHidden},
	{ID: "N7", Cost: map[string]int{"Green": 3, "White": 3, "Blue": 3}, Points: 3, State: entities.CardStateHidden},
	{ID: "N8", Cost: map[string]int{"White": 3, "Blue": 3, "Black": 3}, Points: 3, State: entities.CardStateHidden},
	{ID: "N9", Cost: map[string]int{"Blue": 3, "Black": 3, "Red": 3}, Points: 3, State: entities.CardStateHidden},
	{ID: "N10", Cost: map[string]int{"Black": 3, "Red": 3, "Green": 3}, Points: 3, State: entities.CardStateHidden},
}
